env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[cffac8ba529721f184e6fb7b3e67588585e0ef951e16b534ec5e431fff4576a7e0dd79d7f9a5afa0a6ee0e859660e4fe]"

task:
    name: hgdvbjptysp
    timeout_in: 120m
    container:
      image: ubuntu:rolling
      cpu: 8
      memory: 32G
    system_update_script:
      - ./system_update
    neofetch_script:
      - ./neofetch
    specification_script:
      - ./specification
#    download_ccache_script:
#      - ./download_ccache
    sync_script:
      - ./sync
    build_script:
      - ./build
    upload_ccache_script:
      - ./upload_ccache
