#!/bin/bash

cd /tmp/rom

. build/envsetup.sh
lunch rr_certus-userdebug
export SELINUX_IGNORE_NEVERALLOWS=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_rom(){
	mka bacon
	zip=$(up out/target/product/certus/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom &
sleep 4800 && kill "$!"
