#!/bin/bash

echo "Downloading previous ccache . . . . . ."

# ccache URL file
url=http://soft-frog-09b4.wisnuardiwardana12.workers.dev/ccache.tar.gz

cd /tmp
time aria2c $url -x16 -s50
time tar xf ccache.tar.gz
rm -rf ccache.tar.gz
