#!/bin/bash

echo "Downloading previous ccache . . . . . ."

# ccache URL file
url=https://milimnava.bubbleguum13.workers.dev/0:/Recent%20Upload/ccache.tar.gz

cd /tmp
time aria2c $url -x16 -s50
time tar xf ccache.tar.gz
rm -rf ccache.tar.gz
