#!/bin/bash

echo "Downloading previous ccache . . . . . ."

# ccache URL file
url=https://drive.azhe.space/0:/Data/ccache.tar.gz

cd /tmp
time aria2c $url -x16 -s50
time tar xf ccache.tar.gz
rm -rf ccache.tar.gz

