#!/bin/bash

ROMDIR=/tmp/rom
MANIFEST=https://github.com/ResurrectionRemix/platform_manifest.git
BRANCH=Q

mkdir -p "$ROMDIR"
cd "$ROMDIR"

# Repo init command
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name hisyam99
git config --global user.email hisyamkamil99@gmail.com

# Local Manifests
git clone https://github.com/hisyam99/local_manifests --depth 1 -b certus/vndk-29 .repo/local_manifests

# Sync source with -q
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Replace defconfig
rm -rf kernel/xiaomi/mt6765/arch/arm/configs/certus_defconfig
cd "$ROMDIR"/kernel/xiaomi/mt6765/arch/arm/configs
wget https://del.dog/raw/divuvullan -O certus_defconfig

# bringup resurrection remix
cd "$ROMDIR"/device/xiaomi/certus
rm -rf nad_certus.mk
wget https://del.dog/raw/ifuppufuxu -O rr_certus.mk
mv nad.dependencies rr.dependencies
sed -i "s/nad/rr/" AndroidProducts.mk

# Replace device.mk
rm -rf device.mk
wget https://del.dog/raw/lagryloloc -O device.mk

# Replace BoardConfig
rm -rf BoardConfig.mk
wget https://raw.githubusercontent.com/hisyam99/BoardConfig_Certus/main/BoardConfig.mk

# SafetyNet
cd "$ROMDIR"/system/security
wget -c https://github.com/ProtonAOSP/android_system_security/commit/9dd88a70668da3d7b0581489d55d0d1a2ced2f5c.patch
git am 9dd88a70668da3d7b0581489d55d0d1a2ced2f5c.patch

# ....
cd "$ROMDIR"/packages/apps/Settings
rm -rf res/values/resurrection_device_maintainers_strings.xml
rm -rf res/xml/device_maintainers_fragment.xml
wget https://www.hisyam99.workers.dev/resurrection_device_maintainers_strings.xml -O res/values/resurrection_device_maintainers_strings.xml
wget https://www.hisyam99.workers.dev/device_maintainers_fragment.xml -O res/xml/device_maintainers_fragment.xml

# Back to ROM Directory
cd "$ROMDIR"
