#!/bin/bash

ROMDIR=/tmp/rom
MANIFEST=https://github.com/ResurrectionRemix/platform_manifest.git
BRANCH=Q

mkdir -p "$ROMDIR"
cd "$ROMDIR"

# Repo init command
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name hisyam99
git config --global user.email hisyamkamil99@gmail.com

# Local Manifests
git clone https://github.com/hisyam99/local_manifests --depth 1 -b certus/vndk-29 .repo/local_manifests

# Sync source with -q
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Fix sepolicy related issue
rm -rf device/mediatek/sepolicy/basic/non_plat/file.te
cd "$ROMDIR"/device/mediatek/sepolicy/basic/non_plat
curl https://del.dog/raw/ryxanukipp -o file.te

# Replace defconfig
rm -rf kernel/xiaomi/mt6765/arch/arm/configs/certus_defconfig
cd "$ROMDIR"/kernel/xiaomi/mt6765/arch/arm/configs
curl https://del.dog/raw/divuvullan -o certus_defconfig

# bringup resurrection remix
cd "$ROMDIR"/device/xiaomi/certus
rm -rf nad_certus.mk
curl https://del.dog/raw/ifuppufuxu -o rr_certus.mk
mv nad.dependencies rr.dependencies
sed -i "s/nad/rr/" AndroidProducts.mk

# Replace device.mk
rm -rf device.mk
curl https://del.dog/raw/lagryloloc -o device.mk

# Replace BoardConfig
rm -rf BoardConfig.mk
curl https://raw.githubusercontent.com/hisyam99/BoardConfig_Certus/main/BoardConfig.mk -o BoardConfig.mk

# SafetyNet
cd "$ROMDIR"/system/security
wget -c https://github.com/ProtonAOSP/android_system_security/commit/9dd88a70668da3d7b0581489d55d0d1a2ced2f5c.patch
git am 9dd88a70668da3d7b0581489d55d0d1a2ced2f5c.patch

# Back to ROM Directory
cd "$ROMDIR"
